controller_ip       = ""
controller_username = ""
controller_password = ""
account_name        = ""
location            = ""
transit_gw_size     = ""
spoke_gw_size       = ""
firewall_size       = ""
